// This file was generated by [ts-rs]. Do not edit this file manually.

export type FileChangeType = "added" | "modified" | "deleted" | "renamed" | "unmerged";

export type FileStatusDto = { path: string, staged: FileChangeType | null, unstaged: FileChangeType | null, };

export type CommitInfoDto = { id: string, summary: string, author: string, relative_time: string, };

export type RepoInfoDto = { repo_id: string, root_path: string, name: string, is_bare: boolean, };

export type RepoStatusDto = { repo_id: string, root_path: string, branch: string, ahead: number, behind: number, has_untracked: boolean, has_staged: boolean, has_unstaged: boolean, conflicted_files: number, modified_files: Array<FileStatusDto>, latest_commit: CommitInfoDto | null, };

export type DiffStatDto = { files_changed: number, insertions: number, deletions: number, };

export type BranchInfoDto = { name: string, current: boolean, last_commit: string, ahead: number, behind: number, };

export type RemoteInfoDto = { name: string, fetch: string, push: string, };

export type WorktreeInfoDto = { branch: string, path: string, };