#[cfg(test)]
mod tests {
    use crate::git::{BranchInfoDto, CommitInfoDto, DiffStatDto, FileChangeType, FileStatusDto, RepoStatusDto};
    use std::fs;
    use std::path::PathBuf;
    use ts_rs::TS;

    #[test]
    fn export_bindings() {
        let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
        let types_dir = PathBuf::from(manifest_dir).parent().unwrap().join("src/types");

        fs::create_dir_all(&types_dir).unwrap();

        // git.ts
        // Add a header to indicate generation
        let mut git_ts = String::from("// This file was generated by [ts-rs]. Do not edit this file manually.\n\n");
        git_ts.push_str(&FileChangeType::decl());
        git_ts.push_str("\n\n");
        git_ts.push_str(&FileStatusDto::decl());
        git_ts.push_str("\n\n");
        git_ts.push_str(&CommitInfoDto::decl());
        git_ts.push_str("\n\n");
        git_ts.push_str(&RepoStatusDto::decl());
        git_ts.push_str("\n\n");
        git_ts.push_str(&DiffStatDto::decl());
        git_ts.push_str("\n\n");
        git_ts.push_str(&BranchInfoDto::decl());
        
        fs::write(types_dir.join("git.ts"), git_ts).unwrap();

    }
}
