// This module contains tests to verify TypeScript types are up to date.
// To regenerate types, run: cargo run --bin export_types --manifest-path src-tauri/Cargo.toml

#[cfg(test)]
mod tests {
    use crate::git::{
        BranchInfoDto, CommitInfoDto, DiffCompareKind, DiffDeltaStatus, DiffFileSummaryDto,
        DiffMetaDto, DiffRequestDto, DiffRequestOptionsDto, DiffResponseDto, DiffStatDto,
        FileChangeType, FileStats, FileStatusDto, RemoteInfoDto, RepoInfoDto, RepoStatusDto,
        StashInfoDto, SubmoduleInfoDto, TagInfoDto, WorktreeInfoDto,
    };
    use std::fs;
    use std::path::PathBuf;
    use ts_rs::TS;

    /// Test that verifies the TypeScript types file is up to date with Rust DTOs.
    /// If this test fails, run: cargo run --bin export_types --manifest-path src-tauri/Cargo.toml
    #[test]
    fn types_are_synced() {
        let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
        let types_dir = PathBuf::from(manifest_dir).parent().unwrap().join("src/types");
        let git_ts_path = types_dir.join("git.ts");

        // Generate expected types in memory
        let mut expected_ts = String::from("// This file was generated by [ts-rs]. Do not edit this file manually.\n");
        expected_ts.push_str("// To regenerate: cargo run --bin export_types --manifest-path src-tauri/Cargo.toml\n\n");
        expected_ts.push_str(&FileChangeType::decl().replace("type ", "export type "));
        expected_ts.push_str("\n\n");
        expected_ts.push_str(&FileStats::decl().replace("type ", "export type "));
        expected_ts.push_str("\n\n");
        expected_ts.push_str(&FileStatusDto::decl().replace("type ", "export type "));
        expected_ts.push_str("\n\n");
        expected_ts.push_str(&CommitInfoDto::decl().replace("type ", "export type "));
        expected_ts.push_str("\n\n");
        expected_ts.push_str(&RepoInfoDto::decl().replace("type ", "export type "));
        expected_ts.push_str("\n\n");
        expected_ts.push_str(&RepoStatusDto::decl().replace("type ", "export type "));
        expected_ts.push_str("\n\n");
        expected_ts.push_str(&DiffStatDto::decl().replace("type ", "export type "));
        expected_ts.push_str("\n\n");
        expected_ts.push_str(&DiffCompareKind::decl().replace("type ", "export type "));
        expected_ts.push_str("\n\n");
        expected_ts.push_str(&DiffDeltaStatus::decl().replace("type ", "export type "));
        expected_ts.push_str("\n\n");
        expected_ts.push_str(&DiffRequestOptionsDto::decl().replace("type ", "export type "));
        expected_ts.push_str("\n\n");
        expected_ts.push_str(&DiffRequestDto::decl().replace("type ", "export type "));
        expected_ts.push_str("\n\n");
        expected_ts.push_str(&DiffFileSummaryDto::decl().replace("type ", "export type "));
        expected_ts.push_str("\n\n");
        expected_ts.push_str(&DiffMetaDto::decl().replace("type ", "export type "));
        expected_ts.push_str("\n\n");
        expected_ts.push_str(&DiffResponseDto::decl().replace("type ", "export type "));
        expected_ts.push_str("\n\n");
        expected_ts.push_str(&BranchInfoDto::decl().replace("type ", "export type "));
        expected_ts.push_str("\n\n");
        expected_ts.push_str(&RemoteInfoDto::decl().replace("type ", "export type "));
        expected_ts.push_str("\n\n");
        expected_ts.push_str(&SubmoduleInfoDto::decl().replace("type ", "export type "));
        expected_ts.push_str("\n\n");
        expected_ts.push_str(&WorktreeInfoDto::decl().replace("type ", "export type "));
        expected_ts.push_str("\n\n");
        expected_ts.push_str(&StashInfoDto::decl().replace("type ", "export type "));
        expected_ts.push_str("\n\n");
        expected_ts.push_str(&TagInfoDto::decl().replace("type ", "export type "));

        // Read actual types file
        let actual_ts = fs::read_to_string(&git_ts_path)
            .unwrap_or_else(|_| {
                panic!(
                    "TypeScript types file not found at {}. \
                    Run: cargo run --bin export_types --manifest-path src-tauri/Cargo.toml",
                    git_ts_path.display()
                )
            });

        // Compare
        if expected_ts != actual_ts {
            panic!(
                "TypeScript types are out of sync with Rust DTOs.\n\
                Run: cargo run --bin export_types --manifest-path src-tauri/Cargo.toml\n\
                File: {}",
                git_ts_path.display()
            );
        }
    }
}
