#[cfg(test)]
mod tests {
    use crate::git::{
        BranchInfoDto, CommitInfoDto, DiffCompareKind, DiffDeltaStatus, DiffFileSummaryDto,
        DiffMetaDto, DiffRequestDto, DiffRequestOptionsDto, DiffResponseDto, DiffStatDto,
        FileChangeType, FileStatusDto, RemoteInfoDto, RepoInfoDto, RepoStatusDto, StashInfoDto,
        WorktreeInfoDto,
    };
    use std::fs;
    use std::path::PathBuf;
    use ts_rs::TS;

    #[test]
    fn export_bindings() {
        let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
        let types_dir = PathBuf::from(manifest_dir).parent().unwrap().join("src/types");

        fs::create_dir_all(&types_dir).unwrap();

        // git.ts
        // Add a header to indicate generation
        let mut git_ts = String::from("// This file was generated by [ts-rs]. Do not edit this file manually.\n\n");
        git_ts.push_str(&FileChangeType::decl().replace("type ", "export type "));
        git_ts.push_str("\n\n");
        git_ts.push_str(&FileStatusDto::decl().replace("type ", "export type "));
        git_ts.push_str("\n\n");
        git_ts.push_str(&CommitInfoDto::decl().replace("type ", "export type "));
        git_ts.push_str("\n\n");
        git_ts.push_str(&RepoInfoDto::decl().replace("type ", "export type "));
        git_ts.push_str("\n\n");
        git_ts.push_str(&RepoStatusDto::decl().replace("type ", "export type "));
        git_ts.push_str("\n\n");
        git_ts.push_str(&DiffStatDto::decl().replace("type ", "export type "));
        git_ts.push_str("\n\n");
        git_ts.push_str(&DiffCompareKind::decl().replace("type ", "export type "));
        git_ts.push_str("\n\n");
        git_ts.push_str(&DiffDeltaStatus::decl().replace("type ", "export type "));
        git_ts.push_str("\n\n");
        git_ts.push_str(&DiffRequestOptionsDto::decl().replace("type ", "export type "));
        git_ts.push_str("\n\n");
        git_ts.push_str(&DiffRequestDto::decl().replace("type ", "export type "));
        git_ts.push_str("\n\n");
        git_ts.push_str(&DiffFileSummaryDto::decl().replace("type ", "export type "));
        git_ts.push_str("\n\n");
        git_ts.push_str(&DiffMetaDto::decl().replace("type ", "export type "));
        git_ts.push_str("\n\n");
        git_ts.push_str(&DiffResponseDto::decl().replace("type ", "export type "));
        git_ts.push_str("\n\n");
        git_ts.push_str(&BranchInfoDto::decl().replace("type ", "export type "));
        git_ts.push_str("\n\n");
        git_ts.push_str(&RemoteInfoDto::decl().replace("type ", "export type "));
        git_ts.push_str("\n\n");
        git_ts.push_str(&WorktreeInfoDto::decl().replace("type ", "export type "));
        git_ts.push_str("\n\n");
        git_ts.push_str(&StashInfoDto::decl().replace("type ", "export type "));
        
        fs::write(types_dir.join("git.ts"), git_ts).unwrap();

    }
}
